dist: trusty
language: python
matrix:
    include:
        - python: 3.6
          env: KERAS_BACKEND=tensorflow MODE=INTEGRATION_TESTS
        - python: 3.6
          env: KERAS_BACKEND=tensorflow
install:
  # code below is taken from http://conda.pydata.org/docs/travis.html
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - travis_retry conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment

  - travis_retry pip install --only-binary=numpy,scipy,pandas numpy nose scipy h5py pytest pytest-pep8 pandas --progress-bar off

  # set library path
  - export LD_LIBRARY_PATH=$HOME/miniconda/envs/test-environment/lib/:$LD_LIBRARY_PATH

    # install pydot for visualization tests
  - travis_retry conda install -q $MKL pydot graphviz Pillow

  - pip install -e .[tests] --progress-bar off

  # install TensorFlow
  - pip install tensorflow --progress-bar off

# command to run tests
script:
  - export MKL_THREADING_LAYER="GNU"
  - if [[ "$MODE" == "INTEGRATION_TESTS" ]]; then
      PYTHONPATH=$PWD:$PYTHONPATH py.test tests/integration_tests;
    else
      PYTHONPATH=$PWD:$PYTHONPATH py.test tests/ --ignore=tests/integration_tests --ignore=tests/docs --ignore=tests/keras/legacy/layers_test.py --ignore=tests/test_api.py --cov-config .coveragerc --cov=keras tests/;
    fi
