# Copyright (c) 2019 Parsa Amini
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

version: 2
anchors:
    - &docker_config
        docker:
            - image: stellargroup/phylanx:devel
              entrypoint: /bin/bash


################################################################################
jobs:
    build_test:
        <<: *docker_config
        working_directory: /keras
        steps:
            - checkout:
                path:
                    /keras
            # Dependencies
            - run:
                command: pip3 install wheel
            - run:
                command: pip3 install tensorflow
            - run:
                command: pip3 install -e .[tests]
            - run:
                command: find . -name '*.pyc' -delete
            - run:
                command: |
                    py.test tests/ -v -k backend \
                        --ignore=tests/integration_tests \
                        --ignore=tests/test_documentation.py \
                        --ignore=tests/keras/legacy/layers_test.py \
                        --ignore=tests/keras/engine/test_topology.py \
                        --disable-pytest-warnings

################################################################################
workflows:
    version: 2
    build_and_test:
        jobs:
            - build_test

