site_name: Keras Documentation
#theme: readthedocs
docs_dir: sources
repo_url: http://github.com/fchollet/keras
site_url: http://keras.io/
theme_dir: theme
site_description: Documentation for fast and lightweight Keras Deep Learning library.

dev_addr: '0.0.0.0:8000'
google_analytics: ['UA-61785484-1', 'keras.io']


pages:
- Home: index.md
- Index: documentation.md
- Examples: examples.md
- Optimizers: optimizers.md
- Objectives: objectives.md
- Models: models.md
- Activations: activations.md
- Initializations: initializations.md
- Regularizers: regularizers.md
- Constraints: constraints.md
- Callbacks: callbacks.md
- Datasets: datasets.md
- Layers:
  - Core Layers: layers/core.md
  - Convolutional Layers: layers/convolutional.md
  - Recurrent Layers: layers/recurrent.md
  - Advanced Activations Layers: layers/advanced_activations.md
  - Normalization Layers: layers/normalization.md
  - Embedding Layers: layers/embeddings.md
  - Noise layers: layers/noise.md
  - Containers: layers/containers.md
- Preprocessing:
  - Sequence Preprocessing: preprocessing/sequence.md
  - Text Preprocessing: preprocessing/text.md
  - Image Preprocessing: preprocessing/image.md

