site_name: Keras Documentation
theme: readthedocs
# theme_dir: theme
docs_dir: sources
repo_url: http://github.com/keras-team/keras
site_url: http://keras.io/
site_description: 'Documentation for Keras, the Python Deep Learning library.'

dev_addr: '0.0.0.0:8000'
google_analytics: ['UA-61785484-1', 'keras.io']

pages:
- Home: index.md
- Why use Keras: why-use-keras.md
- Getting started:
  - Guide to the Sequential model: getting-started/sequential-model-guide.md
  - Guide to the Functional API: getting-started/functional-api-guide.md
  - FAQ: getting-started/faq.md
- Models:
  - About Keras models: models/about-keras-models.md
  - Sequential: models/sequential.md
  - Model (functional API): models/model.md
- Layers:
  - About Keras layers: layers/about-keras-layers.md
  - Core Layers: layers/core.md
  - Convolutional Layers: layers/convolutional.md
  - Pooling Layers: layers/pooling.md
  - Locally-connected Layers: layers/local.md
  - Recurrent Layers: layers/recurrent.md
  - Embedding Layers: layers/embeddings.md
  - Merge Layers: layers/merge.md
  - Advanced Activations Layers: layers/advanced-activations.md
  - Normalization Layers: layers/normalization.md
  - Noise layers: layers/noise.md
  - Layer wrappers: layers/wrappers.md
  - Writing your own Keras layers: layers/writing-your-own-keras-layers.md
- Preprocessing:
  - Sequence Preprocessing: preprocessing/sequence.md
  - Text Preprocessing: preprocessing/text.md
  - Image Preprocessing: preprocessing/image.md
- Losses: losses.md
- Metrics: metrics.md
- Optimizers: optimizers.md
- Activations: activations.md
- Callbacks: callbacks.md
- Datasets: datasets.md
- Applications: applications.md
- Backend: backend.md
- Initializers: initializers.md
- Regularizers: regularizers.md
- Constraints: constraints.md
- Visualization: visualization.md
- Scikit-learn API: scikit-learn-api.md
- Utils: utils.md
- Contributing: contributing.md
